### ISSUE TITLE
[Bug]: failing tests in _tests/erc721-consecutive.rs_  

### ISSUE THREAD

**Issue by 0xNeshi** [OpenZeppelin/rust-contracts-stylus#286]
### What happened?

Followed the [guidelines](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/main/GUIDELINES.md) and installed all the necessary nightly builds. After running `./scripts/e2e-tests.sh`, the _tests/erc721-consecutive.rs_ tests were failing with the following output:

```console
     Running tests/erc721-consecutive.rs (target/debug/deps/erc721_consecutive-3d27de35530b233d)

running 6 tests
test error_when_exceed_batch_size ... FAILED
test error_when_to_is_zero ... FAILED
test constructs ... FAILED
test burns ... FAILED
test mints ... FAILED
test transfers_from ... FAILED

failures:

---- error_when_exceed_batch_size stdout ----
110877347320130
wasm data fee: Ξ0.000111
thread 'error_when_exceed_batch_size' panicked at /home/nenad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/koba-0.2.0/src/assembler/labeler.rs:69:40:
Label 'data_c167b0e3c82238f4f2d1a50a8b3a44f96311d77b148c30dc0ef863e1a060dcb6' not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- error_when_to_is_zero stdout ----
110877347320130
wasm data fee: Ξ0.000111
thread 'error_when_to_is_zero' panicked at /home/nenad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/koba-0.2.0/src/assembler/labeler.rs:69:40:
Label 'data_c167b0e3c82238f4f2d1a50a8b3a44f96311d77b148c30dc0ef863e1a060dcb6' not found

---- constructs stdout ----
110877347320130
wasm data fee: Ξ0.000111
thread 'constructs' panicked at /home/nenad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/koba-0.2.0/src/assembler/labeler.rs:69:40:
Label 'data_c167b0e3c82238f4f2d1a50a8b3a44f96311d77b148c30dc0ef863e1a060dcb6' not found

---- burns stdout ----
110877347320130
wasm data fee: Ξ0.000111
thread 'burns' panicked at /home/nenad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/koba-0.2.0/src/assembler/labeler.rs:69:40:
Label 'data_c167b0e3c82238f4f2d1a50a8b3a44f96311d77b148c30dc0ef863e1a060dcb6' not found

---- mints stdout ----
110877347320130
wasm data fee: Ξ0.000111
thread 'mints' panicked at /home/nenad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/koba-0.2.0/src/assembler/labeler.rs:69:40:
Label 'data_c167b0e3c82238f4f2d1a50a8b3a44f96311d77b148c30dc0ef863e1a060dcb6' not found

---- transfers_from stdout ----
110877347320130
wasm data fee: Ξ0.000111
thread 'transfers_from' panicked at /home/nenad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/koba-0.2.0/src/assembler/labeler.rs:69:40:
Label 'data_c167b0e3c82238f4f2d1a50a8b3a44f96311d77b148c30dc0ef863e1a060dcb6' not found


failures:
    burns
    constructs
    error_when_exceed_batch_size
    error_when_to_is_zero
    mints
    transfers_from

test result: FAILED. 0 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 7.09s

error: test failed, to rerun pass `-p erc721-consecutive-example --test erc721-consecutive`
```

### platform

- [X] linux
- [ ] windows
- [ ] macos

### Expected behavior

Tests in _tests/erc721-consecutive.rs_ should have passed.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by bidzyyys** [comment]
Hi @0xNeshi!
Thank you for submitting this issue. 
Have you followed all the steps from this CI build?
https://github.com/OpenZeppelin/rust-contracts-stylus/actions/runs/10848468137/job/30105638596

**Comment by 0xNeshi** [comment]
Running tests with exact specs from CI build (solc@0.8.24, cairo-stylus@0.5.1) results in passing tests! :heavy_check_mark: 
I was originally running them with solc@0.8.27 and cairo-stylus@0.5.3.

Should this still be considered a bug then or are tests expected to fail with newer pkg versions?

P.S. [Documentation on running E2E tests](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/main/GUIDELINES.md#running-end-to-end-tests) is out of sync in any case, I can create a new issue to update it, does that sound good?

**Comment by qalisander** [comment]
Now the documentation is updated. Currently we're temporarily tied to the older version of solidity. We will wait till Offchain Labs adds constructors to the stylus-sdk.
